### ISSUE TITLE
monte_carlo.py

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Probability-Programs#10]
write `monte_carlo.py` in `book_programs/chapter_2/`
the mathematica script can be found in `contributing/mathematica_scripts/Book Programs.3.0/Chapter 2(3.0)/MonteCarlo.Chpt2.mat.m`

make sure to start by copying the template found in `contributing/`

**Comment by tincher** [comment]
In the Mathematica code, one can define a custom function to be used.
How should this be handled?
I do not know of a way to provide a custom python function from the command line.
Should there be a fixed set of functions, for example, only the ones used in the math module?

**Comment by tincher** [comment]
So I did a version where you can put in the name of any math function.
You can have a look at it at [here](https://github.com/tincher/Probability-Programs/tree/monte_carlo).

**Comment by FireLemons** [comment]
I think a good solution would be to have the custom function be in the script to modify. 
and have documentation of the function to be called somewhere in the usage hint

**Comment by tincher** [comment]
PR #24 
![Figure_1](https://user-images.githubusercontent.com/29018283/97080599-d7b77b00-15fc-11eb-8ad2-88c980a10ff9.png)
