### ISSUE TITLE
darts.py

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Probability-Programs#11]
write `darts.py` in `book_programs/chapter_2/`
the mathematica script can be found in `contributing/mathematica_scripts/Book Programs.3.0/Chapter 2(3.0)/Darts.Chpt2.mat.m`

make sure to start by copying the template found in `contributing/`

**Comment by tincher** [comment]
PR #17 
Sample output for 100 Darts
![Figure_1](https://user-images.githubusercontent.com/29018283/95762325-d8bbe480-0cad-11eb-93ca-2467b856079b.png)
