### ISSUE TITLE
buffons_needle.py

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Probability-Programs#13]
write `buffons_needle.py` in `book_programs/chapter_2/`
the mathematica script can be found in `contributing/mathematica_scripts/Book Programs.3.0/Chapter 2(3.0)/BuffonsNeedle.Chpt2.mat.m`

make sure to start by copying the template found in `contributing/`

**Comment by VPraharsha03** [comment]
PR https://github.com/FireLemons/Probability-Programs/pull/16

Buffon's Needle Simulation. Here's a sample output for 500 needles
![Output](https://user-images.githubusercontent.com/56556436/95652172-dec68f80-0b0c-11eb-8246-186a46c5b3d9.png)
