### ISSUE TITLE
bertrands_paradox.py

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Probability-Programs#14]
write `bertrands_paradox.py` in `book_programs/chapter_2/`
the mathematica script can be found in `contributing/mathematica_scripts/Book Programs.3.0/Chapter 2(3.0)/BertrandsParadox.Chpt2.mat.m`

make sure to start by copying the template found in `contributing/`

**Comment by VPraharsha03** [comment]
PR: https://github.com/FireLemons/Probability-Programs/pull/18
100 chords plotted with a sample size of 1000
Here's the console output: 
![console-op](https://user-images.githubusercontent.com/56556436/95948501-47b04f00-0e0e-11eb-8cec-461736179953.png)
And simulation
#Method 1
![Method_1](https://user-images.githubusercontent.com/56556436/95948536-5860c500-0e0e-11eb-9266-5dd4b024b796.png)
#Method 2
![Method_2](https://user-images.githubusercontent.com/56556436/95948551-5d257900-0e0e-11eb-976a-fbe997d9c79e.png)
#Method 3
![Method_3](https://user-images.githubusercontent.com/56556436/95948557-5e56a600-0e0e-11eb-923f-1f1a10c0b2e8.png)
