### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by FireLemons** [FireLemons/Probability-Programs#8]
Add windows install instructions to the readme.  

To complete this issue, show a screenshot of the graphs output by running `python3 h_t_simulation.py 50 100` on your windows system.  

`h_t_simulation.py` can be found in `book_programs/chapter_1/`

**Comment by VPraharsha03** [comment]
PR: https://github.com/FireLemons/Probability-Programs/pull/15

obtained output
![code](https://user-images.githubusercontent.com/56556436/95604214-f8b49380-0a74-11eb-94de-c0962fb40ae7.jpg)
![output](https://user-images.githubusercontent.com/56556436/95604232-feaa7480-0a74-11eb-990c-6f6712a5fb01.jpg)
